version: "3"
volumes:
    node_modules_front:
services:
  front:
    image: node:fermium
    volumes:
      - ./:/src
      - node_modules_front:/src/node_modules
    working_dir: /src
    command: tail -f /dev/null
    ports: 
      - 3000:3000
  api:
    build: ./
    volumes:
      - ./:/src
    working_dir: /src
    entrypoint: tail -f /dev/null
